config/routes.rb
Language::Application.routes.draw do
  resources :languagestrings

  match 'languagestrings/:id/:locale' => 'languagestrings#find_by_stringid_and_locale'

end

app/models/languagestring.rb
class Languagestring < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/languagestrings_controller.rb
class LanguagestringsController < ApplicationController
  # GET /languagestrings
  # GET /languagestrings.json
  def index
    @languagestrings = Languagestring.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @languagestrings }
    end
  end

  # GET /languagestrings/1
  # GET /languagestrings/1.json
  def show
    @languagestring = Languagestring.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @languagestring }
    end
  end

  # GET /languagestrings/new
  # GET /languagestrings/new.json
  def new
    @languagestring = Languagestring.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @languagestring }
    end
  end

  # GET /languagestrings/1/edit
  def edit
    @languagestring = Languagestring.find(params[:id])
  end

  # POST /languagestrings
  # POST /languagestrings.json
  def create
    @languagestring = Languagestring.new(params[:languagestring])

    respond_to do |format|
      if @languagestring.save
        format.html { redirect_to @languagestring, notice: 'Languagestring was successfully created.' }
        format.json { render json: @languagestring, status: :created, location: @languagestring }
      else
        format.html { render action: "new" }
        format.json { render json: @languagestring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /languagestrings/1
  # PUT /languagestrings/1.json
  def update
    @languagestring = Languagestring.find(params[:id])

    respond_to do |format|
      if @languagestring.update_attributes(params[:languagestring])
        format.html { redirect_to @languagestring, notice: 'Languagestring was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @languagestring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languagestrings/1
  # DELETE /languagestrings/1.json
  def destroy
    @languagestring = Languagestring.find(params[:id])
    @languagestring.destroy

    respond_to do |format|
      format.html { redirect_to languagestrings_url }
      format.json { head :no_content }
    end
  end

  def find_by_stringid_and_locale
    @languagestring = Languagestring.find_by_stringid_and_locale(params[:id],params[:locale])
    debugger
    respond_to do |format|
      format.html { render json: @languagestring }
      format.json { render json: @languagestring }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languagestrings_helper.rb
module LanguagestringsHelper
end

app/views/languagestrings/_form.html.erb
<%= form_for(@languagestring) do |f| %>
  <% if @languagestring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@languagestring.errors.count, "error") %> prohibited this languagestring from being saved:</h2>

      <ul>
      <% @languagestring.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languagestrings/edit.html.erb
<h1>Editing languagestring</h1>

<%= render 'form' %>

<%= link_to 'Show', @languagestring %> |
<%= link_to 'Back', languagestrings_path %>

app/views/languagestrings/index.html.erb
<h1>Listing languagestrings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @languagestrings.each do |languagestring| %>
  <tr>
    <td><%= link_to 'Show', languagestring %></td>
    <td><%= link_to 'Edit', edit_languagestring_path(languagestring) %></td>
    <td><%= link_to 'Destroy', languagestring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Languagestring', new_languagestring_path %>

app/views/languagestrings/new.html.erb
<h1>New languagestring</h1>

<%= render 'form' %>

<%= link_to 'Back', languagestrings_path %>

app/views/languagestrings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_languagestring_path(@languagestring) %> |
<%= link_to 'Back', languagestrings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Language</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>